title: Debbie
description: The minimal PHP test library with beautiful test reports
theme: jekyll-theme-minimal
show_downloads: true
logo: /assets/images/debbie-logo.png
github:
  repository_url: https://github.com/CaboLabs/Debbie
  zip_url: https://github.com/CaboLabs/Debbie/archive/refs/heads/master.zip
  tar_url: https://github.com/CaboLabs/Debbie/archive/refs/heads/master.tar.gz